import { ItemRecomendationsProps } from "../components/home/busket/ItemRecomendations";

export const list1: ItemRecomendationsProps[] = [
    {
        key: 1,
        imgPath: "/png/product1.png",
        imgHover: "/png/potato.png",
        stars: 4.5,
        price: 19.99,
        describe: "Печенье заварное 'Ракушка' с шоколадной начинкой.",
    },
    {
        key: 2,
        imgPath: "/png/product2.png",
        imgHover: "/png/instagram2.png",
        stars: 5,
        price: 24.99,
        describe: "Пирожное 'Картошка' с нежным кремом.",
    },
    {
        key: 3,
        imgPath: "/png/product3.png",
        imgHover: "/png/dog.png",
        stars: 3.8,
        price: 14.99,
        describe: "Медовик с грецкими орехами.",
    },
    {
        key: 4,
        imgPath: "/png/product4.png",
        imgHover: "/png/cookiesBusket.jpg",
        stars: 4.2,
        price: 29.99,
        describe: "Торт 'Наполеон' с воздушным кремом.",
    },
    {
        key: 5,
        imgPath: "/png/product5.png",
        imgHover: "/png/ChinaSoup.jpg",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
    },
    {
        key: 6,
        imgPath: "/png/ChinaSoup.jpg",
        imgHover: "/png/product5.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
    },
    {
        key: 7,
        imgPath: "/png/cookiesBusket.jpg",
        imgHover: "/png/product4.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
    },
    {
        key: 8,
        imgPath: "/png/dog.png",
        imgHover: "/png/product3.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
    },
    {
        key: 9,
        imgPath: "/png/instagram2.png",
        imgHover: "/png/product2.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
    },
    {
        key: 10,
        imgPath: "/png/potato.png",
        imgHover: "/png/product1.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
    },
    {
        key: 11,
        imgPath: "/png/product1.png",
        imgHover: "/png/potato.png",
        stars: 3.9,
        price: 18.99,
        describe: "Хрустящее печенье с карамелью.",
    },
    {
        key: 12,
        imgPath: "/png/product2.png",
        imgHover: "/png/instagram2.png",
        stars: 5,
        price: 25.99,
        describe: "Классическое пирожное с ванилью.",
    },
    {
        key: 13,
        imgPath: "/png/product3.png",
        imgHover: "/png/dog.png",
        stars: 4.2,
        price: 15.49,
        describe: "Шоколадный медовик с орехами.",
    },
    {
        key: 14,
        imgPath: "/png/product4.png",
        imgHover: "/png/cookiesBusket.jpg",
        stars: 4.6,
        price: 30.99,
        describe: "Воздушный торт 'Наполеон'.",
    },
    {
        key: 15,
        imgPath: "/png/product5.png",
        imgHover: "/png/ChinaSoup.jpg",
        stars: 4.8,
        price: 23.99,
        describe: "Эклеры с клубничным кремом.",
    },
    {
        key: 16,
        imgPath: "/png/ChinaSoup.jpg",
        imgHover: "/png/product5.png",
        stars: 4.1,
        price: 21.50,
        describe: "Горячий суп с пряностями.",
    },
    {
        key: 17,
        imgPath: "/png/cookiesBusket.jpg",
        imgHover: "/png/product4.png",
        stars: 4.3,
        price: 16.99,
        describe: "Ассорти из французского печенья.",
    },
    {
        key: 18,
        imgPath: "/png/dog.png",
        imgHover: "/png/product3.png",
        stars: 4.0,
        price: 19.99,
        describe: "Домашний бисквит с вареньем.",
    },
    {
        key: 19,
        imgPath: "/png/instagram2.png",
        imgHover: "/png/product2.png",
        stars: 3.5,
        price: 20.49,
        describe: "Шоколадное пирожное с орехами.",
    },
    {
        key: 20,
        imgPath: "/png/potato.png",
        imgHover: "/png/product1.png",
        stars: 4.9,
        price: 22.99,
        describe: "Пирожное 'Картошка' по классическому рецепту.",
    },
];



export const list2: ItemRecomendationsProps[] = [
    {
        key: 11,
        imgPath: "/png/ChinaSoup.png",
        imgHover: "/png/product4.png",
        stars: 3,
        price: 14,
        describe: "Красивые капибары в зоопарке",
    },
    {
        key: 12,
        imgPath: "/png/cookiesBusket.png",
        imgHover: "/png/product3.png",
        stars: 4,
        price: 14,
        describe: "Цюриха или закаты недружественных",
    },
    {
        key: 13,
        imgPath: "/png/product3.png",
        imgHover: "/png/cookiesBusket.png",
        stars: 4.9,
        price: 14,
        describe: "Стран. Ты захочешь вернуться,",
    },
    {
        key: 14,
        imgPath: "/png/product4.png",
        imgHover: "/png/ChinaSoup.png",
        stars: 2.4,
        price: 14,
        describe: "Но просрочен загран",
    },
];

