import { CheckRadioProps, InputType } from "@/components/home/busket/CheckRadio";
import { ItemRecomendationsProps, ProductType, TagsCard } from "../components/home/busket/ItemRecomendations";

export const list1: ItemRecomendationsProps[] = [
    {
        id: 1,
        imgPath: "/png/product1.png",
        imgHover: "/png/potato.png",
        stars: 4.5,
        price: 19.99,
        describe: "Печенье заварное 'Ракушка' с шоколадной начинкой.",
        type: ProductType.Breakfast,
        TagCard: TagsCard.New,
    },
    {
        id: 2,
        imgPath: "/png/product2.png",
        imgHover: "/png/instagram2.png",
        stars: 5,
        price: 24.99,
        describe: "Пирожное 'Картошка' с нежным кремом.",
        type: ProductType.PostLaunch,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 3,
        imgPath: "/png/product3.png",
        imgHover: "/png/dog.png",
        stars: 3.8,
        price: 14.99,
        describe: "Медовик с грецкими орехами.",
        type: ProductType.Launch,
        TagCard: TagsCard.Percent,
    },
    {
        id: 4,
        imgPath: "/png/product4.png",
        imgHover: "/png/cookiesBusket.jpg",
        stars: 4.2,
        price: 29.99,
        describe: "Торт 'Наполеон' с воздушным кремом.",
        type: ProductType.Grocery,
    },
    {
        id: 5,
        imgPath: "/png/product5.png",
        imgHover: "/png/ChinaSoup.jpg",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.Oil,
        TagCard: TagsCard.New,
    },
    {
        id: 6,
        imgPath: "/png/ChinaSoup.jpg",
        imgHover: "/png/product5.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.Sous,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 7,
        imgPath: "/png/cookiesBusket.jpg",
        imgHover: "/png/product4.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.Breakfast,
    },
    {
        id: 8,
        imgPath: "/png/dog.png",
        imgHover: "/png/product3.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.PostLaunch,
        TagCard: TagsCard.Percent,
    },
    {
        id: 9,
        imgPath: "/png/instagram2.png",
        imgHover: "/png/product2.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.Launch,
    },
    {
        id: 10,
        imgPath: "/png/potato.png",
        imgHover: "/png/product1.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.Grocery,
        TagCard: TagsCard.New,
    },
    {
        id: 11,
        imgPath: "/png/product1.png",
        imgHover: "/png/potato.png",
        stars: 3.9,
        price: 18.99,
        describe: "Хрустящее печенье с карамелью.",
        type: ProductType.Oil,
    },
    {
        id: 12,
        imgPath: "/png/product2.png",
        imgHover: "/png/instagram2.png",
        stars: 5,
        price: 25.99,
        describe: "Классическое пирожное с ванилью.",
        type: ProductType.Sous,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 13,
        imgPath: "/png/product3.png",
        imgHover: "/png/dog.png",
        stars: 4.2,
        price: 15.49,
        describe: "Шоколадный медовик с орехами.",
        type: ProductType.Breakfast,
    },
    {
        id: 14,
        imgPath: "/png/product4.png",
        imgHover: "/png/cookiesBusket.jpg",
        stars: 4.6,
        price: 30.99,
        describe: "Воздушный торт 'Наполеон'.",
        type: ProductType.PostLaunch,
        TagCard: TagsCard.Percent,
    },
    {
        id: 15,
        imgPath: "/png/product5.png",
        imgHover: "/png/ChinaSoup.jpg",
        stars: 4.8,
        price: 23.99,
        describe: "Эклеры с клубничным кремом.",
        type: ProductType.Launch,
    },
    {
        id: 16,
        imgPath: "/png/ChinaSoup.jpg",
        imgHover: "/png/product5.png",
        stars: 4.1,
        price: 21.50,
        describe: "Горячий суп с пряностями.",
        type: ProductType.Grocery,
    },
    {
        id: 17,
        imgPath: "/png/cookiesBusket.jpg",
        imgHover: "/png/product4.png",
        stars: 4.3,
        price: 16.99,
        describe: "Ассорти из французского печенья.",
        type: ProductType.Oil,
        TagCard: TagsCard.New,
    },
    {
        id: 18,
        imgPath: "/png/dog.png",
        imgHover: "/png/product3.png",
        stars: 4.0,
        price: 19.99,
        describe: "Домашний бисквит с вареньем.",
        type: ProductType.Sous,
    },
    {
        id: 19,
        imgPath: "/png/instagram2.png",
        imgHover: "/png/product2.png",
        stars: 3.5,
        price: 20.49,
        describe: "Шоколадное пирожное с орехами.",
        type: ProductType.Breakfast,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 20,
        imgPath: "/png/potato.png",
        imgHover: "/png/product1.png",
        stars: 4.9,
        price: 22.99,
        describe: "Пирожное 'Картошка' по классическому рецепту.",
        type: ProductType.PostLaunch,
    },
    {
        id: 21,
        imgPath: "/png/product1.png",
        imgHover: "/png/potato.png",
        stars: 4.3,
        price: 17.99,
        describe: "Творожное печенье с ванилью.",
        type: ProductType.Launch,
        TagCard: TagsCard.Percent,
    },
    {
        id: 22,
        imgPath: "/png/product2.png",
        imgHover: "/png/instagram2.png",
        stars: 4.6,
        price: 23.49,
        describe: "Карамельный эклер с шоколадной глазурью.",
        type: ProductType.Breakfast,
    },
    {
        id: 23,
        imgPath: "/png/product3.png",
        imgHover: "/png/dog.png",
        stars: 4.8,
        price: 19.79,
        describe: "Шоколадный кекс с орехами.",
        type: ProductType.Grocery,
    },
    {
        id: 24,
        imgPath: "/png/product4.png",
        imgHover: "/png/cookiesBusket.jpg",
        stars: 4.1,
        price: 27.99,
        describe: "Торт 'Медовик' с вареной сгущенкой.",
        type: ProductType.Oil,
        TagCard: TagsCard.New,
    },
    {
        id: 25,
        imgPath: "/png/product5.png",
        imgHover: "/png/ChinaSoup.jpg",
        stars: 4.9,
        price: 21.99,
        describe: "Воздушные профитроли с кремом.",
        type: ProductType.Sous,
    },
    {
        id: 26,
        imgPath: "/png/ChinaSoup.jpg",
        imgHover: "/png/product5.png",
        stars: 4.5,
        price: 20.49,
        describe: "Пряный овощной суп с лапшой.",
        type: ProductType.Launch,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 27,
        imgPath: "/png/cookiesBusket.jpg",
        imgHover: "/png/product4.png",
        stars: 4.0,
        price: 18.99,
        describe: "Набор французского печенья 'Мадлен'.",
        type: ProductType.PostLaunch,
    },
    {
        id: 28,
        imgPath: "/png/dog.png",
        imgHover: "/png/product3.png",
        stars: 4.3,
        price: 22.99,
        describe: "Бисквитный рулет с малиновым джемом.",
        type: ProductType.Breakfast,
    },
    {
        id: 29,
        imgPath: "/png/instagram2.png",
        imgHover: "/png/product2.png",
        stars: 3.9,
        price: 19.50,
        describe: "Трюфельные конфеты с фундуком.",
        type: ProductType.Grocery,
        TagCard: TagsCard.Percent,
    },
    {
        id: 30,
        imgPath: "/png/potato.png",
        imgHover: "/png/product1.png",
        stars: 5.0,
        price: 25.99,
        describe: "Торт 'Прага' с шоколадным кремом.",
        type: ProductType.Oil,
    },
    {
        id: 31,
        imgPath: "/png/product1.png",
        imgHover: "/png/potato.png",
        stars: 4.4,
        price: 15.99,
        describe: "Шоколадное печенье с кусочками какао-бобов.",
        type: ProductType.Sous,
    },
    {
        id: 32,
        imgPath: "/png/product2.png",
        imgHover: "/png/instagram2.png",
        stars: 4.7,
        price: 24.79,
        describe: "Классический чизкейк с ванилью.",
        type: ProductType.Launch,
        TagCard: TagsCard.New,
    },
    {
        id: 33,
        imgPath: "/png/product3.png",
        imgHover: "/png/dog.png",
        stars: 4.2,
        price: 18.49,
        describe: "Ванильный кекс с цедрой лимона.",
        type: ProductType.PostLaunch,
    },
    {
        id: 34,
        imgPath: "/png/product4.png",
        imgHover: "/png/cookiesBusket.jpg",
        stars: 4.9,
        price: 32.99,
        describe: "Муссовый торт с клубникой и сливками.",
        type: ProductType.Breakfast,
    },
    {
        id: 35,
        imgPath: "/png/product5.png",
        imgHover: "/png/ChinaSoup.jpg",
        stars: 4.6,
        price: 21.49,
        describe: "Ореховое пирожное с шоколадным кремом.",
        type: ProductType.Grocery,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 36,
        imgPath: "/png/ChinaSoup.jpg",
        imgHover: "/png/product5.png",
        stars: 4.0,
        price: 19.79,
        describe: "Традиционный японский суп с водорослями.",
        type: ProductType.Oil,
    },
    {
        id: 37,
        imgPath: "/png/cookiesBusket.jpg",
        imgHover: "/png/product4.png",
        stars: 4.5,
        price: 26.49,
        describe: "Торт 'Тирамису' с кофе и какао.",
        type: ProductType.Sous,
    },
    {
        id: 38,
        imgPath: "/png/dog.png",
        imgHover: "/png/product3.png",
        stars: 4.8,
        price: 22.79,
        describe: "Французский круассан с миндальным кремом.",
        type: ProductType.Launch,
        TagCard: TagsCard.Percent,
    },
    {
        id: 39,
        imgPath: "/png/instagram2.png",
        imgHover: "/png/product2.png",
        stars: 3.7,
        price: 20.49,
        describe: "Пирог с яблоками и корицей.",
        type: ProductType.PostLaunch,
    },
    {
        id: 40,
        imgPath: "/png/potato.png",
        imgHover: "/png/product1.png",
        stars: 4.9,
        price: 23.99,
        describe: "Классический кекс с изюмом и орехами.",
        type: ProductType.Breakfast,
        TagCard: TagsCard.New,
    },
];

export const radioTest: CheckRadioProps[] = [
    { type: InputType.Radio, id: "zavtraki", label: "Завтраки", name: "food", typeProduct: ProductType.Breakfast, checked: false},
    { type: InputType.Radio, id: "poldniki", label: "Полдники", name: "food", typeProduct: ProductType.PostLaunch, checked: false},
    { type: InputType.Radio, id: "obedi", label: "Обеды", name: "food", typeProduct: ProductType.Launch, checked: false },
    { type: InputType.Radio, id: "bakaleya", label: "Бакалея", name: "food", typeProduct: ProductType.Grocery, checked: false },
    { type: InputType.Radio, id: "maslo", label: "Масла", name: "food", typeProduct: ProductType.Oil, checked: false },
    { type: InputType.Radio, id: "sousi", label: "Соусы", name: "food", typeProduct: ProductType.Sous, checked: false }
];
