import { CheckRadioProps, InputType } from "@/components/home/busket/CheckRadio";
import { ItemRecomendationsProps, ProductType, TagsCard } from "../components/home/busket/ItemRecomendations";



export interface mokeListInt{
    id: number,
    typeProduct: ProductType
    name: string,
    countProduct: number,
    weight: number,
    ingredients: string,
    stars: number,
    price: number,
    imgs: string[],
    describe: string,
    nutritionalValue: {
        protein: number,
        fats: number,
        carbohydrates: number
        vitamins?: string,
        minerals?: string
    },
    energyValue: number
}


export const mokeList: mokeListInt[] = [
    {
        id: 1,
        typeProduct: ProductType.Breakfast,
        name: "Печенье заварное 'Ракушка' с шоколадной начинкой.",
        countProduct: 1,
        weight: 430,
        ingredients: "Молоко, сахар, творог",
        stars: 4.7,
        price: 14,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Красивые капибары в зоопарке Цюриха или закаты недружественных стран",
        nutritionalValue: {
            protein: 14,
            fats: 15,
            carbohydrates: 16,
            vitamins: "B2, B3",
            minerals: "Кальций, фосфор, свинец"
        },
        energyValue: 1234,
    },
    {
        id: 2,
        typeProduct: ProductType.PostLaunch,
        name: "Суп китайский с лапшой",
        countProduct: 1,
        weight: 500,
        ingredients: "Лапша, курица, овощи",
        stars: 4.5,
        price: 20,
        imgs: ["/png/ChinaSoup.jpg", "/png/product2.png", "/png/product3.png"],
        describe: "Ароматный суп с лапшой и курицей",
        nutritionalValue: {
            protein: 10,
            fats: 8,
            carbohydrates: 30,
            vitamins: "A, C",
            minerals: "Железо, цинк"
        },
        energyValue: 800,
    },
    {
        id: 3,
        typeProduct: ProductType.Launch,
        name: "Картофель запеченный с сыром",
        countProduct: 1,
        weight: 350,
        ingredients: "Картофель, сыр, масло",
        stars: 4.8,
        price: 18,
        imgs: ["/png/potato.png", "/png/product1.png", "/png/product5.png"],
        describe: "Запеченный картофель с сыром и зеленью",
        nutritionalValue: {
            protein: 8,
            fats: 12,
            carbohydrates: 40,
            vitamins: "B6, C",
            minerals: "Калий, магний"
        },
        energyValue: 950,
    },
    {
        id: 4,
        typeProduct: ProductType.Grocery,
        name: "Корзина печенья",
        countProduct: 1,
        weight: 600,
        ingredients: "Мука, сахар, масло",
        stars: 4.6,
        price: 25,
        imgs: ["/png/cookiesBusket.jpg", "/png/product2.png", "/png/product3.png"],
        describe: "Корзина с разнообразным печеньем",
        nutritionalValue: {
            protein: 5,
            fats: 20,
            carbohydrates: 50,
            vitamins: "B1, B2",
            minerals: "Кальций, железо"
        },
        energyValue: 1200,
    },
    {
        id: 5,
        typeProduct: ProductType.Oil,
        name: "Оливковое масло",
        countProduct: 1,
        weight: 250,
        ingredients: "Оливки",
        stars: 4.9,
        price: 30,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Натуральное оливковое масло высшего качества",
        nutritionalValue: {
            protein: 0,
            fats: 100,
            carbohydrates: 0,
            vitamins: "E, K",
            minerals: "Кальций, железо"
        },
        energyValue: 900,
    },
    {
        id: 6,
        typeProduct: ProductType.Sous,
        name: "Соус барбекю",
        countProduct: 1,
        weight: 200,
        ingredients: "Томаты, сахар, специи",
        stars: 4.4,
        price: 10,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Пикантный соус для барбекю",
        nutritionalValue: {
            protein: 2,
            fats: 5,
            carbohydrates: 20,
            vitamins: "C, B6",
            minerals: "Калий, натрий"
        },
        energyValue: 500,
    },
    {
        id: 7,
        typeProduct: ProductType.Breakfast,
        name: "Омлет с овощами",
        countProduct: 1,
        weight: 300,
        ingredients: "Яйца, помидоры, перец, лук",
        stars: 4.6,
        price: 12,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Сочный омлет с свежими овощами",
        nutritionalValue: {
            protein: 15,
            fats: 10,
            carbohydrates: 5,
            vitamins: "A, C",
            minerals: "Кальций, железо"
        },
        energyValue: 350,
    },
    {
        id: 8,
        typeProduct: ProductType.PostLaunch,
        name: "Фруктовый салат",
        countProduct: 1,
        weight: 250,
        ingredients: "Яблоки, бананы, апельсины, йогурт",
        stars: 4.8,
        price: 8,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Свежий фруктовый салат с йогуртом",
        nutritionalValue: {
            protein: 3,
            fats: 2,
            carbohydrates: 20,
            vitamins: "C, B6",
            minerals: "Калий, магний"
        },
        energyValue: 200,
    },
    {
        id: 9,
        typeProduct: ProductType.Launch,
        name: "Гречневая каша с грибами",
        countProduct: 1,
        weight: 400,
        ingredients: "Гречка, грибы, лук, масло",
        stars: 4.7,
        price: 15,
        imgs: ["/png/potato.png", "/png/product1.png", "/png/product5.png"],
        describe: "Ароматная гречневая каша с грибами",
        nutritionalValue: {
            protein: 10,
            fats: 8,
            carbohydrates: 50,
            vitamins: "B1, B2",
            minerals: "Железо, магний"
        },
        energyValue: 600,
    },
    {
        id: 10,
        typeProduct: ProductType.Grocery,
        name: "Макароны из твердых сортов пшеницы",
        countProduct: 1,
        weight: 500,
        ingredients: "Мука, вода",
        stars: 4.5,
        price: 10,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Качественные макароны для ваших блюд",
        nutritionalValue: {
            protein: 12,
            fats: 2,
            carbohydrates: 70,
            vitamins: "B1, B3",
            minerals: "Железо, цинк"
        },
        energyValue: 800,
    },
    {
        id: 11,
        typeProduct: ProductType.Oil,
        name: "Подсолнечное масло",
        countProduct: 1,
        weight: 1000,
        ingredients: "Семена подсолнечника",
        stars: 4.7,
        price: 25,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Натуральное подсолнечное масло",
        nutritionalValue: {
            protein: 0,
            fats: 100,
            carbohydrates: 0,
            vitamins: "E",
            minerals: "Фосфор"
        },
        energyValue: 900,
    },
    {
        id: 12,
        typeProduct: ProductType.Sous,
        name: "Сырный соус",
        countProduct: 1,
        weight: 200,
        ingredients: "Сыр, сливки, специи",
        stars: 4.6,
        price: 12,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Нежный сырный соус для пасты и закусок",
        nutritionalValue: {
            protein: 8,
            fats: 20,
            carbohydrates: 5,
            vitamins: "A, B12",
            minerals: "Кальций, фосфор"
        },
        energyValue: 450,
    },
    {
        id: 13,
        typeProduct: ProductType.Breakfast,
        name: "Блинчики с медом",
        countProduct: 1,
        weight: 300,
        ingredients: "Мука, молоко, яйца, мед",
        stars: 4.9,
        price: 10,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Нежные блинчики с натуральным медом",
        nutritionalValue: {
            protein: 8,
            fats: 10,
            carbohydrates: 40,
            vitamins: "B1, B2",
            minerals: "Кальций, железо"
        },
        energyValue: 500,
    },
    {
        id: 14,
        typeProduct: ProductType.PostLaunch,
        name: "Йогурт с ягодами",
        countProduct: 1,
        weight: 200,
        ingredients: "Йогурт, клубника, черника",
        stars: 4.7,
        price: 7,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Натуральный йогурт с свежими ягодами",
        nutritionalValue: {
            protein: 5,
            fats: 3,
            carbohydrates: 15,
            vitamins: "C, B6",
            minerals: "Кальций, магний"
        },
        energyValue: 250,
    },
    {
        id: 15,
        typeProduct: ProductType.Launch,
        name: "Плов с бараниной",
        countProduct: 1,
        weight: 500,
        ingredients: "Рис, баранина, морковь, лук",
        stars: 4.8,
        price: 22,
        imgs: ["/png/potato.png", "/png/product1.png", "/png/product5.png"],
        describe: "Ароматный плов с нежной бараниной",
        nutritionalValue: {
            protein: 20,
            fats: 15,
            carbohydrates: 60,
            vitamins: "B1, B3",
            minerals: "Железо, цинк"
        },
        energyValue: 900,
    },
    {
        id: 16,
        typeProduct: ProductType.Grocery,
        name: "Рис басмати",
        countProduct: 1,
        weight: 1000,
        ingredients: "Рис",
        stars: 4.6,
        price: 18,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Ароматный рис басмати для ваших блюд",
        nutritionalValue: {
            protein: 7,
            fats: 1,
            carbohydrates: 80,
            vitamins: "B1, B3",
            minerals: "Магний, фосфор"
        },
        energyValue: 700,
    },
    {
        id: 17,
        typeProduct: ProductType.Oil,
        name: "Кокосовое масло",
        countProduct: 1,
        weight: 500,
        ingredients: "Кокос",
        stars: 4.8,
        price: 35,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Натуральное кокосовое масло для готовки и ухода",
        nutritionalValue: {
            protein: 0,
            fats: 100,
            carbohydrates: 0,
            vitamins: "E, K",
            minerals: "Железо, цинк"
        },
        energyValue: 900,
    },
    {
        id: 18,
        typeProduct: ProductType.Sous,
        name: "Томатный соус",
        countProduct: 1,
        weight: 300,
        ingredients: "Томаты, лук, чеснок, специи",
        stars: 4.5,
        price: 9,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Классический томатный соус для пасты и пиццы",
        nutritionalValue: {
            protein: 3,
            fats: 5,
            carbohydrates: 15,
            vitamins: "C, A",
            minerals: "Калий, магний"
        },
        energyValue: 300,
    },
    {
        id: 19,
        typeProduct: ProductType.Breakfast,
        name: "Сырники с вареньем",
        countProduct: 1,
        weight: 350,
        ingredients: "Творог, мука, яйца, варенье",
        stars: 4.8,
        price: 12,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Нежные сырники с домашним вареньем",
        nutritionalValue: {
            protein: 15,
            fats: 10,
            carbohydrates: 30,
            vitamins: "B2, B12",
            minerals: "Кальций, фосфор"
        },
        energyValue: 600,
    },
    {
        id: 20,
        typeProduct: ProductType.PostLaunch,
        name: "Смузи с бананом и шпинатом",
        countProduct: 1,
        weight: 300,
        ingredients: "Бананы, шпинат, йогурт",
        stars: 4.7,
        price: 9,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Освежающий смузи с бананом и шпинатом",
        nutritionalValue: {
            protein: 5,
            fats: 2,
            carbohydrates: 25,
            vitamins: "C, A",
            minerals: "Калий, магний"
        },
        energyValue: 300,
    },
    {
        id: 21,
        typeProduct: ProductType.Launch,
        name: "Куриный суп с лапшой",
        countProduct: 1,
        weight: 450,
        ingredients: "Курица, лапша, морковь, лук",
        stars: 4.6,
        price: 16,
        imgs: ["/png/potato.png", "/png/product1.png", "/png/product5.png"],
        describe: "Ароматный куриный суп с лапшой",
        nutritionalValue: {
            protein: 12,
            fats: 8,
            carbohydrates: 30,
            vitamins: "A, C",
            minerals: "Кальций, железо"
        },
        energyValue: 700,
    },
    {
        id: 22,
        typeProduct: ProductType.Grocery,
        name: "Овсяные хлопья",
        countProduct: 1,
        weight: 1000,
        ingredients: "Овес",
        stars: 4.7,
        price: 12,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Натуральные овсяные хлопья для полезного завтрака",
        nutritionalValue: {
            protein: 10,
            fats: 5,
            carbohydrates: 60,
            vitamins: "B1, B6",
            minerals: "Магний, железо"
        },
        energyValue: 800,
    },
    {
        id: 23,
        typeProduct: ProductType.Oil,
        name: "Льняное масло",
        countProduct: 1,
        weight: 500,
        ingredients: "Семена льна",
        stars: 4.8,
        price: 28,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Полезное льняное масло для здоровья",
        nutritionalValue: {
            protein: 0,
            fats: 100,
            carbohydrates: 0,
            vitamins: "E, K",
            minerals: "Омега-3, Омега-6"
        },
        energyValue: 900,
    },
    {
        id: 24,
        typeProduct: ProductType.Sous,
        name: "Чесночный соус",
        countProduct: 1,
        weight: 200,
        ingredients: "Чеснок, майонез, сметана",
        stars: 4.5,
        price: 8,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Пикантный чесночный соус для закусок",
        nutritionalValue: {
            protein: 2,
            fats: 15,
            carbohydrates: 5,
            vitamins: "C, B6",
            minerals: "Кальций, фосфор"
        },
        energyValue: 400,
    },
    {
        id: 25,
        typeProduct: ProductType.Breakfast,
        name: "Творожная запеканка",
        countProduct: 1,
        weight: 400,
        ingredients: "Творог, яйца, сахар, изюм",
        stars: 4.8,
        price: 14,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Нежная творожная запеканка с изюмом",
        nutritionalValue: {
            protein: 15,
            fats: 10,
            carbohydrates: 25,
            vitamins: "B2, B12",
            minerals: "Кальций, фосфор"
        },
        energyValue: 600,
    },
    {
        id: 26,
        typeProduct: ProductType.PostLaunch,
        name: "Сэндвич с курицей",
        countProduct: 1,
        weight: 300,
        ingredients: "Курица, хлеб, салат, помидоры",
        stars: 4.7,
        price: 10,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Сытный сэндвич с курицей и овощами",
        nutritionalValue: {
            protein: 12,
            fats: 8,
            carbohydrates: 30,
            vitamins: "A, C",
            minerals: "Кальций, железо"
        },
        energyValue: 500,
    },
    {
        id: 27,
        typeProduct: ProductType.Launch,
        name: "Гуляш с говядиной",
        countProduct: 1,
        weight: 500,
        ingredients: "Говядина, лук, морковь, томаты",
        stars: 4.8,
        price: 20,
        imgs: ["/png/potato.png", "/png/product1.png", "/png/product5.png"],
        describe: "Ароматный гуляш с нежной говядиной",
        nutritionalValue: {
            protein: 20,
            fats: 15,
            carbohydrates: 25,
            vitamins: "B1, B3",
            minerals: "Железо, цинк"
        },
        energyValue: 800,
    },
    {
        id: 28,
        typeProduct: ProductType.Grocery,
        name: "Гречневая крупа",
        countProduct: 1,
        weight: 1000,
        ingredients: "Гречка",
        stars: 4.7,
        price: 15,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Натуральная гречневая крупа для полезных блюд",
        nutritionalValue: {
            protein: 12,
            fats: 3,
            carbohydrates: 70,
            vitamins: "B1, B2",
            minerals: "Железо, магний"
        },
        energyValue: 700,
    },
    {
        id: 29,
        typeProduct: ProductType.Oil,
        name: "Кунжутное масло",
        countProduct: 1,
        weight: 500,
        ingredients: "Кунжут",
        stars: 4.8,
        price: 32,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Ароматное кунжутное масло для азиатской кухни",
        nutritionalValue: {
            protein: 0,
            fats: 100,
            carbohydrates: 0,
            vitamins: "E, K",
            minerals: "Кальций, магний"
        },
        energyValue: 900,
    },
    {
        id: 30,
        typeProduct: ProductType.Sous,
        name: "Соус терияки",
        countProduct: 1,
        weight: 250,
        ingredients: "Соевый соус, сахар, чеснок, имбирь",
        stars: 4.6,
        price: 11,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Классический соус терияки для азиатских блюд",
        nutritionalValue: {
            protein: 3,
            fats: 5,
            carbohydrates: 20,
            vitamins: "B6, C",
            minerals: "Натрий, калий"
        },
        energyValue: 450,
    },
    {
        id: 31,
        typeProduct: ProductType.Breakfast,
        name: "Каша овсяная с фруктами",
        countProduct: 1,
        weight: 350,
        ingredients: "Овсянка, молоко, яблоки, бананы",
        stars: 4.8,
        price: 9,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Полезная овсяная каша с свежими фруктами",
        nutritionalValue: {
            protein: 8,
            fats: 5,
            carbohydrates: 40,
            vitamins: "B1, C",
            minerals: "Кальций, магний"
        },
        energyValue: 500,
    },
    {
        id: 32,
        typeProduct: ProductType.PostLaunch,
        name: "Салат Цезарь",
        countProduct: 1,
        weight: 300,
        ingredients: "Курица, салат, сухарики, сыр",
        stars: 4.7,
        price: 14,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Классический салат Цезарь с курицей",
        nutritionalValue: {
            protein: 15,
            fats: 10,
            carbohydrates: 20,
            vitamins: "A, C",
            minerals: "Кальций, железо"
        },
        energyValue: 600,
    },
    {
        id: 33,
        typeProduct: ProductType.Launch,
        name: "Рыбный суп",
        countProduct: 1,
        weight: 500,
        ingredients: "Рыба, картофель, морковь, лук",
        stars: 4.6,
        price: 18,
        imgs: ["/png/potato.png", "/png/product1.png", "/png/product5.png"],
        describe: "Ароматный рыбный суп с овощами",
        nutritionalValue: {
            protein: 18,
            fats: 10,
            carbohydrates: 25,
            vitamins: "B1, B3",
            minerals: "Йод, фосфор"
        },
        energyValue: 700,
    },
    {
        id: 34,
        typeProduct: ProductType.Grocery,
        name: "Чечевица",
        countProduct: 1,
        weight: 1000,
        ingredients: "Чечевица",
        stars: 4.7,
        price: 14,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Полезная чечевица для супов и салатов",
        nutritionalValue: {
            protein: 25,
            fats: 2,
            carbohydrates: 60,
            vitamins: "B1, B6",
            minerals: "Железо, магний"
        },
        energyValue: 800,
    },
    {
        id: 35,
        typeProduct: ProductType.Oil,
        name: "Масло авокадо",
        countProduct: 1,
        weight: 500,
        ingredients: "Авокадо",
        stars: 4.8,
        price: 40,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Полезное масло авокадо для салатов и готовки",
        nutritionalValue: {
            protein: 0,
            fats: 100,
            carbohydrates: 0,
            vitamins: "E, K",
            minerals: "Калий, магний"
        },
        energyValue: 900,
    },
    {
        id: 36,
        typeProduct: ProductType.Sous,
        name: "Соус песто",
        countProduct: 1,
        weight: 200,
        ingredients: "Базилик, оливковое масло, кедровые орехи",
        stars: 4.7,
        price: 15,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Ароматный соус песто для пасты и закусок",
        nutritionalValue: {
            protein: 5,
            fats: 20,
            carbohydrates: 5,
            vitamins: "A, C",
            minerals: "Кальций, железо"
        },
        energyValue: 450,
    },
    {
        id: 37,
        typeProduct: ProductType.Breakfast,
        name: "Яичница с беконом",
        countProduct: 1,
        weight: 300,
        ingredients: "Яйца, бекон, лук",
        stars: 4.7,
        price: 12,
        imgs: ["/png/product1.png", "/png/potato.png", "/png/product5.png"],
        describe: "Сытная яичница с хрустящим беконом",
        nutritionalValue: {
            protein: 15,
            fats: 20,
            carbohydrates: 5,
            vitamins: "B12, D",
            minerals: "Кальций, железо"
        },
        energyValue: 600,
    },
    {
        id: 38,
        typeProduct: ProductType.PostLaunch,
        name: "Фруктовый йогурт",
        countProduct: 1,
        weight: 200,
        ingredients: "Йогурт, персики, клубника",
        stars: 4.8,
        price: 7,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Нежный йогурт с кусочками фруктов",
        nutritionalValue: {
            protein: 5,
            fats: 3,
            carbohydrates: 20,
            vitamins: "C, B6",
            minerals: "Кальций, магний"
        },
        energyValue: 250,
    },
    {
        id: 39,
        typeProduct: ProductType.Launch,
        name: "Борщ с говядиной",
        countProduct: 1,
        weight: 500,
        ingredients: "Говядина, свекла, капуста, картофель",
        stars: 4.8,
        price: 18,
        imgs: ["/png/potato.png", "/png/product1.png", "/png/product5.png"],
        describe: "Наваристый борщ с говядиной и овощами",
        nutritionalValue: {
            protein: 15,
            fats: 10,
            carbohydrates: 30,
            vitamins: "A, C",
            minerals: "Железо, калий"
        },
        energyValue: 700,
    },
    {
        id: 40,
        typeProduct: ProductType.Grocery,
        name: "Кукурузная крупа",
        countProduct: 1,
        weight: 1000,
        ingredients: "Кукуруза",
        stars: 4.6,
        price: 10,
        imgs: ["/png/product2.png", "/png/product3.png", "/png/product1.png"],
        describe: "Кукурузная крупа для каш и гарниров",
        nutritionalValue: {
            protein: 8,
            fats: 3,
            carbohydrates: 70,
            vitamins: "B1, B3",
            minerals: "Железо, магний"
        },
        energyValue: 750,
    }
];

// Продолжайте добавлять объекты до 40

export const list1: ItemRecomendationsProps[] = [
    {
        id: 1,
        imgPath: "/png/product1.png",
        imgHover: "/png/potato.png",
        stars: 4.5,
        price: 19.99,
        describe: "Печенье заварное 'Ракушка' с шоколадной начинкой.",
        type: ProductType.Breakfast,
        TagCard: TagsCard.New,
    },
    {
        id: 2,
        imgPath: "/png/product2.png",
        imgHover: "/png/instagram2.png",
        stars: 5,
        price: 24.99,
        describe: "Пирожное 'Картошка' с нежным кремом.",
        type: ProductType.PostLaunch,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 3,
        imgPath: "/png/product3.png",
        imgHover: "/png/dog.png",
        stars: 3.8,
        price: 14.99,
        describe: "Медовик с мамаой вадима и грецкими орехами.",
        type: ProductType.Launch,
        TagCard: TagsCard.Percent,
    },
    {
        id: 4,
        imgPath: "/png/product4.png",
        imgHover: "/png/cookiesBusket.jpg",
        stars: 4.2,
        price: 29.99,
        describe: "Торт 'Наполеон' с воздушным кремом.",
        type: ProductType.Grocery,
    },
    {
        id: 5,
        imgPath: "/png/product5.png",
        imgHover: "/png/ChinaSoup.jpg",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.Oil,
        TagCard: TagsCard.New,
    },
    {
        id: 6,
        imgPath: "/png/ChinaSoup.jpg",
        imgHover: "/png/product5.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.Sous,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 7,
        imgPath: "/png/cookiesBusket.jpg",
        imgHover: "/png/product4.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.Breakfast,
    },
    {
        id: 8,
        imgPath: "/png/dog.png",
        imgHover: "/png/product3.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.PostLaunch,
        TagCard: TagsCard.Percent,
    },
    {
        id: 9,
        imgPath: "/png/instagram2.png",
        imgHover: "/png/product2.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.Launch,
    },
    {
        id: 10,
        imgPath: "/png/potato.png",
        imgHover: "/png/product1.png",
        stars: 4.7,
        price: 22.99,
        describe: "Эклеры с ванильным кремом.",
        type: ProductType.Grocery,
        TagCard: TagsCard.New,
    },
    {
        id: 11,
        imgPath: "/png/product1.png",
        imgHover: "/png/potato.png",
        stars: 3.9,
        price: 18.99,
        describe: "Хрустящее печенье с карамелью.",
        type: ProductType.Oil,
    },
    {
        id: 12,
        imgPath: "/png/product2.png",
        imgHover: "/png/instagram2.png",
        stars: 5,
        price: 25.99,
        describe: "Классическое пирожное с ванилью.",
        type: ProductType.Sous,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 13,
        imgPath: "/png/product3.png",
        imgHover: "/png/dog.png",
        stars: 4.2,
        price: 15.49,
        describe: "Шоколадный медовик с орехами.",
        type: ProductType.Breakfast,
    },
    {
        id: 14,
        imgPath: "/png/product4.png",
        imgHover: "/png/cookiesBusket.jpg",
        stars: 4.6,
        price: 30.99,
        describe: "Воздушный торт 'Наполеон'.",
        type: ProductType.PostLaunch,
        TagCard: TagsCard.Percent,
    },
    {
        id: 15,
        imgPath: "/png/product5.png",
        imgHover: "/png/ChinaSoup.jpg",
        stars: 4.8,
        price: 23.99,
        describe: "Эклеры с клубничным кремом.",
        type: ProductType.Launch,
    },
    {
        id: 16,
        imgPath: "/png/ChinaSoup.jpg",
        imgHover: "/png/product5.png",
        stars: 4.1,
        price: 21.50,
        describe: "Горячий суп с пряностями.",
        type: ProductType.Grocery,
    },
    {
        id: 17,
        imgPath: "/png/cookiesBusket.jpg",
        imgHover: "/png/product4.png",
        stars: 4.3,
        price: 16.99,
        describe: "Ассорти из французского печенья.",
        type: ProductType.Oil,
        TagCard: TagsCard.New,
    },
    {
        id: 18,
        imgPath: "/png/dog.png",
        imgHover: "/png/product3.png",
        stars: 4.0,
        price: 19.99,
        describe: "Домашний бисквит с вареньем.",
        type: ProductType.Sous,
    },
    {
        id: 19,
        imgPath: "/png/instagram2.png",
        imgHover: "/png/product2.png",
        stars: 3.5,
        price: 20.49,
        describe: "Шоколадное пирожное с орехами.",
        type: ProductType.Breakfast,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 20,
        imgPath: "/png/potato.png",
        imgHover: "/png/product1.png",
        stars: 4.9,
        price: 22.99,
        describe: "Пирожное 'Картошка' по классическому рецепту.",
        type: ProductType.PostLaunch,
    },
    {
        id: 21,
        imgPath: "/png/product1.png",
        imgHover: "/png/potato.png",
        stars: 4.3,
        price: 17.99,
        describe: "Творожное печенье с ванилью.",
        type: ProductType.Launch,
        TagCard: TagsCard.Percent,
    },
    {
        id: 22,
        imgPath: "/png/product2.png",
        imgHover: "/png/instagram2.png",
        stars: 4.6,
        price: 23.49,
        describe: "Карамельный эклер с шоколадной глазурью.",
        type: ProductType.Breakfast,
    },
    {
        id: 23,
        imgPath: "/png/product3.png",
        imgHover: "/png/dog.png",
        stars: 4.8,
        price: 19.79,
        describe: "Шоколадный кекс с орехами.",
        type: ProductType.Grocery,
    },
    {
        id: 24,
        imgPath: "/png/product4.png",
        imgHover: "/png/cookiesBusket.jpg",
        stars: 4.1,
        price: 27.99,
        describe: "Торт 'Медовик' с вареной сгущенкой.",
        type: ProductType.Oil,
        TagCard: TagsCard.New,
    },
    {
        id: 25,
        imgPath: "/png/product5.png",
        imgHover: "/png/ChinaSoup.jpg",
        stars: 4.9,
        price: 21.99,
        describe: "Воздушные профитроли с кремом.",
        type: ProductType.Sous,
    },
    {
        id: 26,
        imgPath: "/png/ChinaSoup.jpg",
        imgHover: "/png/product5.png",
        stars: 4.5,
        price: 20.49,
        describe: "Пряный овощной суп с лапшой.",
        type: ProductType.Launch,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 27,
        imgPath: "/png/cookiesBusket.jpg",
        imgHover: "/png/product4.png",
        stars: 4.0,
        price: 18.99,
        describe: "Набор французского печенья 'Мадлен'.",
        type: ProductType.PostLaunch,
    },
    {
        id: 28,
        imgPath: "/png/dog.png",
        imgHover: "/png/product3.png",
        stars: 4.3,
        price: 22.99,
        describe: "Бисквитный рулет с малиновым джемом.",
        type: ProductType.Breakfast,
    },
    {
        id: 29,
        imgPath: "/png/instagram2.png",
        imgHover: "/png/product2.png",
        stars: 3.9,
        price: 19.50,
        describe: "Трюфельные конфеты с фундуком.",
        type: ProductType.Grocery,
        TagCard: TagsCard.Percent,
    },
    {
        id: 30,
        imgPath: "/png/potato.png",
        imgHover: "/png/product1.png",
        stars: 5.0,
        price: 25.99,
        describe: "Торт 'Прага' с шоколадным кремом.",
        type: ProductType.Oil,
    },
    {
        id: 31,
        imgPath: "/png/product1.png",
        imgHover: "/png/potato.png",
        stars: 4.4,
        price: 15.99,
        describe: "Шоколадное печенье с кусочками какао-бобов.",
        type: ProductType.Sous,
    },
    {
        id: 32,
        imgPath: "/png/product2.png",
        imgHover: "/png/instagram2.png",
        stars: 4.7,
        price: 24.79,
        describe: "Классический чизкейк с ванилью.",
        type: ProductType.Launch,
        TagCard: TagsCard.New,
    },
    {
        id: 33,
        imgPath: "/png/product3.png",
        imgHover: "/png/dog.png",
        stars: 4.2,
        price: 18.49,
        describe: "Ванильный кекс с цедрой лимона.",
        type: ProductType.PostLaunch,
    },
    {
        id: 34,
        imgPath: "/png/product4.png",
        imgHover: "/png/cookiesBusket.jpg",
        stars: 4.9,
        price: 32.99,
        describe: "Муссовый торт с клубникой и сливками.",
        type: ProductType.Breakfast,
    },
    {
        id: 35,
        imgPath: "/png/product5.png",
        imgHover: "/png/ChinaSoup.jpg",
        stars: 4.6,
        price: 21.49,
        describe: "Ореховое пирожное с шоколадным кремом.",
        type: ProductType.Grocery,
        TagCard: TagsCard.Bestseller,
    },
    {
        id: 36,
        imgPath: "/png/ChinaSoup.jpg",
        imgHover: "/png/product5.png",
        stars: 4.0,
        price: 19.79,
        describe: "Традиционный японский суп с водорослями.",
        type: ProductType.Oil,
    },
    {
        id: 37,
        imgPath: "/png/cookiesBusket.jpg",
        imgHover: "/png/product4.png",
        stars: 4.5,
        price: 26.49,
        describe: "Торт 'Тирамису' с кофе и какао.",
        type: ProductType.Sous,
    },
    {
        id: 38,
        imgPath: "/png/dog.png",
        imgHover: "/png/product3.png",
        stars: 4.8,
        price: 22.79,
        describe: "Французский круассан с миндальным кремом.",
        type: ProductType.Launch,
        TagCard: TagsCard.Percent,
    },
    {
        id: 39,
        imgPath: "/png/instagram2.png",
        imgHover: "/png/product2.png",
        stars: 3.7,
        price: 20.49,
        describe: "Пирог с яблоками и корицей.",
        type: ProductType.PostLaunch,
    },
    {
        id: 40,
        imgPath: "/png/potato.png",
        imgHover: "/png/product1.png",
        stars: 4.9,
        price: 23.99,
        describe: "Классический кекс с изюмом и орехами.",
        type: ProductType.Breakfast,
        TagCard: TagsCard.New,
    },
];

export const radioTest: CheckRadioProps[] = [
    { type: InputType.Radio, id: "zavtraki", label: "Завтраки", name: "food", typeProduct: ProductType.Breakfast, checked: false},
    { type: InputType.Radio, id: "poldniki", label: "Полдники", name: "food", typeProduct: ProductType.PostLaunch, checked: false},
    { type: InputType.Radio, id: "obedi", label: "Обеды", name: "food", typeProduct: ProductType.Launch, checked: false },
    { type: InputType.Radio, id: "bakaleya", label: "Бакалея", name: "food", typeProduct: ProductType.Grocery, checked: false },
    { type: InputType.Radio, id: "maslo", label: "Масла", name: "food", typeProduct: ProductType.Oil, checked: false },
    { type: InputType.Radio, id: "sousi", label: "Соусы", name: "food", typeProduct: ProductType.Sous, checked: false }
];
